#How to install Numpy

In [ ]:
pip install numpy

In [ ]:
import numpy as np

# Creat 1-D array

In [ ]:
a=np.array([1,2,3])
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


#New Section

In [ ]:
a = np.array([[1,2,3],[10,20,30]])

In [ ]:
a

array([[ 1,  2,  3],
       [10, 20, 30]])

In [ ]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(2,3,0.1)

array([2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9])

In [ ]:
np.arange(2,10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.linspace(1,4,6)

array([1. , 1.6, 2.2, 2.8, 3.4, 4. ])

In [ ]:
np.indices((2,2))

array([[[0, 0],
        [1, 1]],

       [[0, 1],
        [0, 1]]])

In [ ]:
np.indices((3,3))

array([[[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2]],

       [[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]]])

In [ ]:
a=np.array([1,2,3])
print(a)

[1 2 3]


In [ ]:
print(a.dtype)

int64


# Numpy array vs list memory allocation 

In [ ]:
import numpy as np

l = range(1000)

import sys
a=10
print(sys.getsizeof(a)) #impot allocated to a
print(sys.getsizeof(a)*len(l))
a1= np.arange(1000)
print(a1.size*a1.itemsize)

28
28000
8000


#Numpy Vs List Speed

In [ ]:
import time
import sys

In [ ]:
size = 1000000
l1=range(size)
l2=range(size)

n1 = np.arange(size)
n2 = np.arange(size)

#list itemwise sum
start=time.time()
result=[(x+y) for x,y in zip(l1,l2)]
print((time.time()-start)*1000)
#numpy array itemwise sum
start = time.time()
result1 = n1+n2
print((time.time()-start)*1000)

129.5449733734131
2.8502941131591797


#numpy Operations

In [ ]:
a = np.array([[1,2,3],[10,20,30]])
print(a.ndim)

2


In [ ]:
print(a.itemsize)

8


In [ ]:
print(a.dtype)

int64


In [ ]:
print(a.shape)

(2, 3)


In [ ]:
print(a.size)

6


#Reshape

In [ ]:
a

array([[ 1,  2,  3],
       [10, 20, 30]])

In [ ]:
a.reshape(3,2)

array([[ 1,  2],
       [ 3, 10],
       [20, 30]])

#slicing

In [ ]:
a

array([[ 1,  2,  3],
       [10, 20, 30]])

In [ ]:
a[0,0]

1

In [ ]:
a[0,1]

2

In [ ]:
a[0:2,1:]

array([[ 2,  3],
       [20, 30]])

In [ ]:
a=np.array([[1,2,3,4,5],[10,20,30,40,50]])

In [ ]:
a.shape

(2, 5)

In [ ]:
a[1,2:4]

array([30, 40])

In [ ]:
print(a.min())

1


In [ ]:
print(a.max())

50


In [ ]:
print(a.sum())

165


In [ ]:
print(a)
print(np.sum(a, axis=0)) 
  

print(np.sum(a, axis=1))  

[[ 1  2  3  4  5]
 [10 20 30 40 50]]
[11 22 33 44 55]
[ 15 150]


In [ ]:
# Array Mathematical operations

import numpy as np

x = np.array([[1,2],[3,4]])

y = np.array([[5,6],[7,8]])

print(x)

print(y)

print(x + y)

print(np.add(x, y)) 

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]


In [ ]:
print(x-y)
print(np.subtract(x,y))

[[-4 -4]
 [-4 -4]]
[[-4 -4]
 [-4 -4]]


In [ ]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [ ]:
a = a.reshape(3,2)
print(a)
# another way
np.reshape(a,(2,3))

[[0 1]
 [2 3]
 [4 5]]


array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
print(a)
print(a.size)
np.reshape(a,6)

[[0 1]
 [2 3]
 [4 5]]
6


array([0, 1, 2, 3, 4, 5])

In [ ]:
print(a)

[[0 1]
 [2 3]
 [4 5]]


In [ ]:
print(a.flatten())

[0 1 2 3 4 5]


#Pandas

In [3]:
pip install pandas

In [4]:
import pandas as pd
import numpy as np
a = np.array(['g','o','e','d','u','h','u','b'])
p=pd.Series(a)
print(p)

0    g
1    o
2    e
3    d
4    u
5    h
6    u
7    b
dtype: object


In [5]:
s1 = pd.Series(np.random.random(5),index=['a','b','c','d','e'])

In [6]:
print(type(s1))
print(s1)
print(s1.dtype)

<class 'pandas.core.series.Series'>
a    0.698529
b    0.901501
c    0.819472
d    0.693864
e    0.737126
dtype: float64
float64


In [8]:
data = {'pi':3.14,'e':2.17}
print(data)
s3 = pd.Series(data)
print(s3)

{'pi': 3.14, 'e': 2.17}
pi    3.14
e     2.17
dtype: float64


In [9]:
s = pd.Series(np.random.random(5))
print(s)

0    0.775888
1    0.353859
2    0.391463
3    0.308032
4    0.088793
dtype: float64


In [10]:
s[1]

0.35385851282789016

In [11]:
s[1:3]

1    0.353859
2    0.391463
dtype: float64

In [12]:
print(s.index)

RangeIndex(start=0, stop=5, step=1)


In [13]:
print(s.ndim)

1


In [14]:
print(s.size)

5


In [15]:
print(s.shape)

(5,)
