In [6]:
import sklearn 
import pandas as pd
import numpy as np

In [7]:
from sklearn.datasets import load_iris
iris=load_iris()

iris.keys()


dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [8]:
df=pd.DataFrame(iris['data'])
print(df.head())

     0    1    2    3
0  5.1  3.5  1.4  0.2
1  4.9  3.0  1.4  0.2
2  4.7  3.2  1.3  0.2
3  4.6  3.1  1.5  0.2
4  5.0  3.6  1.4  0.2


In [9]:
print(iris['target_names'])

['setosa' 'versicolor' 'virginica']


In [10]:
iris['feature_names']

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [14]:
X=df
y=iris['target']

In [15]:
#splitting the datasets into training and test set
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(X,y,test_size=0.25,random_state=0)

In [16]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=3)

In [17]:
knn.fit(x_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=3, p=2,
                     weights='uniform')

# prediction and Accuracy

In [18]:
x_new = np.array([[5,2.9,1,0.2]])

In [19]:
prediction = knn.predict(x_new)
prediction

array([0])

In [20]:
iris['target_names'][prediction]

array(['setosa'], dtype='<U10')

#Accuracy

In [22]:
from sklearn.metrics import confusion_matrix, accuracy_score,classification_report

y_pred = knn.predict(x_test)

cm = confusion_matrix(y_test,y_pred)
print(cm)

print(accuracy_score(y_test,y_pred))

[[13  0  0]
 [ 0 15  1]
 [ 0  0  9]]
0.9736842105263158
