#Dhermendra Kumar Tiwari 
#GO_STP_3831
#Task(1,2,3)

#Task-1

In [ ]:
"""1. We are having 3 list like this

Colors = [“Yellow”,”Green”,”White”,”Black”]

Fruits=[“Apple”,”Papaya”,”Mango”,”Orange”]

Animals=[“Tiger”,”Lion”,”Deer”,”Zebra”]

  i. Write a program that asks user to enter a Color/Fruit/Animal name and it should tell which category belongs to , like its is a fruit or color or Animal"""


colors  = ['Yellow','Green','White','Black']
fruits  = ['Apple','Papaya','Mango','Orange']
animals = ['Tiger','Lion','Deer','Zebra']
elem = input("Enter a Color/Fruit or Animal name: ")
if elem in colors:
  print(elem,"is a color")
elif elem in fruits:
  print(elem,"is a fruit")
elif elem in animals:
  print(elem,"is an animal")
else:
  print("Invalid input")

Enter a Color/Fruit or Animal name: Tiger
Tiger is an animal


In [ ]:
"""ii. Write a program that asks user to enter two items and it tells you if they both are in same category or not. 
For example if I enter yellow and Black, it will print "Both are colors" but if I enter yellow and Tiger it should print "They don't belong to same category"""


elem1 = input("Enter first element: ")
elem2 = input("Enter second element: ")
if elem1 in colors and elem2 in colors:
  print("Both are colors")
elif elem1 in fruits and elem2 in fruits:
  print("Both are fruits")
elif elem1 in animals and elem2 in animals:
  print("Both are animals")
else:
  print("They don't belong to same category")


Enter first element: Apple
Enter second element: Tiger
They don't belong to same category


In [ ]:
"""Write a python program that can tell you if your grade score good or not . Normal Score range is 40 to 60.

i. Ask user to enter his score.

ii. If it is below 40 to 60 range then print that score is low

iii. If it is above 60 then print that it is good otherwise print that it is normal"""


score = int(input("Enter your score: "))
if score<40:
  print("Score is low")
elif score>60:
  print("Score is good")
else:
  print("Score is normal")

Enter your score: 80
Score is good


In [ ]:
""".After appearing in exam 10 times you got this result,

result = ["Pass","Fail","Fail","Pass","Fail","Pass","Pass","Fail","Fail","Fail"]

Using for loop figure out how many times you got Pass"""

result = ["Pass","Fail","Fail","Pass","Fail","Pass","Pass","Fail","Fail","Fail"]
count=0
for i in result:
  if i=='Pass':
    count=count+1
print(count)

4


In [ ]:
#Write a program that prints following shape

for i in range(6):
  for j in range(i):
    print('*',end=' ')
  print()
for i in range(4,0,-1):
  for j in range(i):
    print('*',end=' ')
  print()


* 
* * 
* * * 
* * * * 
* * * * * 
* * * * 
* * * 
* * 
* 


In [ ]:
"""Lets say you are running a 50 km race. Write a program that,
Upon completing each 10 km asks you "are you tired?"
If you reply "yes" then it should break and print "you didn't finish the race"
If you reply "no" then it should continue and ask "are you tired" on every km
If you finish all 50 km then it should print congratulations message"""


for i in range(1,51):
  if i%10==0 and i!=50:
    s=input("Are you tired? ")
    if s=='yes':
      print("you didn't finish the race")
      break
    else:
      continue
  if i==50:
      print("Congratulations, you finish the race")

Are you tired? no
Are you tired? no
Are you tired? no
Are you tired? no
Congratulations, you finish the race


In [ ]:
#Write a Python program to find those numbers which are divisible by 7 and multiple of 5, between 1500 and 2700 (both included).


for i in range(1500,2701):
  if i%5==0 and i%7==0:
    print(i,end=' ')

1505 1540 1575 1610 1645 1680 1715 1750 1785 1820 1855 1890 1925 1960 1995 2030 2065 2100 2135 2170 2205 2240 2275 2310 2345 2380 2415 2450 2485 2520 2555 2590 2625 2660 2695 

In [ ]:
#Print square of all numbers between 10 to 20 except even numbers

for i in range(10,20):
  if i%2==0:
    continue
  print(i*i,end=' ')

121 169 225 289 361 

In [ ]:
"""Your Marks for five Test(test1 to test5) looks like this,

marks_list = [65, 75, 2100, 95, 83]

Write a program that asks you to enter marks and program should tell you in which test that marks occurred. If marks is not found then it should print that as well."""

marks_list = [65, 75, 2100, 95, 83]
mark = int(input("Enter your marks: "))
f=0
for i in marks_list:
  if i==mark:
    print('In test',marks_list.index(i),' you secured ',mark)
    f=1
    break
if f==0:
  print("Marks is not found ")

Enter your marks: 66
Marks is not found 


#Task-2

In [ ]:
 #  Is a list mutable? Ans. Yes, list is a Mutable Data type. For e.g.


l=[50,60,70,80,95]
print(l)


l[0]=55
print(l)


[50, 60, 70, 80, 95]
[55, 60, 70, 80, 95]


In [ ]:
 """Does a list need to be homogeneous?

Ans. List need not necessarily homogeneous, it works even if it is heterogeneous....."""


l=['10',15,'Ram','sita']
print(l)



['10', 15, 'Ram', 'sita']


What is the difference between a list and a tuple?

Ans. The Major difference between a list and a tuple is that a list is mutable data type that means any element of a list can be modified whereas tuple is immutable data type that means we cannot modify it after declaring it once.

In [ ]:
#How to find the number of elements in the list?

#1. using in built function
l=[1,2,3,4,5,6,7,8,9]
n=len(l)
print('Number of elements in the list =' ,n)

Number of elements in the list = 9


In [ ]:
#How to check whether the list is empty or not?


lis = []
if len(lis) == 0:
  print("The list is empty")
else:
  print('The list is not empty')

The list is empty


In [ ]:
#How to find the first and last element of the list?

l = [10,20,30,40,50,60,70,80,90]
print('First element of the list = ', l[0])
print('Last element of the list = ', l[-1])

First element of the list =  10
Last element of the list =  90


In [ ]:
#How to find the largest and lowest value in the list?


l = []
num = int(input('Enter number of elements in the list: '))
for n in range(num):
  nums = int(input('Enter the number: '))
  l.append(nums)
  print("Maximum element in the list is :", max(l), "\nMinimum element in the list is :", min(l))

Enter number of elements in the list: 3
Enter the number: 55
Maximum element in the list is : 55 
Minimum element in the list is : 55
Enter the number: 63
Maximum element in the list is : 63 
Minimum element in the list is : 55
Enter the number: 58
Maximum element in the list is : 63 
Minimum element in the list is : 55


In [ ]:
"""How to access elements of the list?

 It can be accessed through index as below..."""


l = [10,20,30,40,50]
print('First element = ',l[0])
print('Second element = ',l[1])
print('Third element = ',l[2])
print('Fourth element = ',l[3])
print('Fifth element = ',l[4])

First element =  10
Second element =  20
Third element =  30
Fourth element =  40
Fifth element =  50


In [ ]:
#Remove elements in a list before a specific index.

l=[1,2,3,4,5,6]
del(l[0:2])
print(l)


[3, 4, 5, 6]


In [ ]:
#Remove elements in a list between 2 indices.

l=[1,2,3,4,5,6]
del(l[1:4])
print(l)

[1, 5, 6]


In [ ]:
#Return every 2nd element in a list between 2 indices.

l=[3,4,5,6,7,8,9,2]
print('new list (between 1st and 6th ele)',l[1:6:2])

new list (between 1st and 6th ele) [4, 6, 8]


In [ ]:
#Get the first element from each nested list in a list.

lst = [['python', 1], ['java', 'c', "net"], [23,7,12]]
print("Given List is:\n",lst)
print("First element from each nested list:\n")
for i in lst:
  print((i[0]))

Given List is:
 [['python', 1], ['java', 'c', 'net'], [23, 7, 12]]
First element from each nested list:

python
java
23


In [ ]:
"""How to modify elements of the list?

Ans. Elements can be modified using index of the list."""

l1 = [0,1,"hello",'hiiiiii',"45",6]
print('List before modification : ',l1)
l1[4] = "bye"
l1[1] = 88
print('List after modification : ',l1)

List before modification :  [0, 1, 'hello', 'hiiiiii', '45', 6]
List after modification :  [0, 88, 'hello', 'hiiiiii', 'bye', 6]


In [ ]:
#How to concatenate two lists?

l1 = [0,1,2,3,4]
l2 = [5,6,7,8,9]
l3 = l1+l2
print(l3)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [ ]:
#How to add two lists element-wise in python?

list1 = [1, 2, 3]
list2 = [4, 5, 6]
sum_list = []  
for i in range(0,len(list1)):
  sum_list.append(list1[i]+list2[i])
  print(sum_list)

[5]
[5, 7]
[5, 7, 9]


In [ ]:
 """Difference between del and clear?

Ans. Clear () function delete the all keys and values in the dictionary and leave the dictionary empty. While del delete the complete dictionary when we want to find deleted dictionary then it will give error that not defined.

 Difference between remove and pop?

Ans. The pop() function will delete the last element from the list whereas the remove() function will delete a particular element by mentioning its index."""

l=[1,2,3,4]
l.pop()
print("After performing pop(): ", l)
l.remove(1)
print("After deleting first element: ", l)

After performing pop():  [1, 2, 3]
After deleting first element:  [2, 3]


In [ ]:
"""Difference between append and extend?

Ans. append() adds a single element to the end of the list while . extend() can add multiple individual elements to the end of the list. 
     append() takes a single element as argument while . extend() takes an iterable as argument

 Difference between indexing and Slicing?

Ans. “Indexing” means referring to an element of an iterable by its position within the iterable. 
     “Slicing” means getting a subset of elements from an iterable based on their indices.

 Difference between sort and sorted?

Ans. The primary difference between the list sort() function and the sorted() function is that the sort() function will modify the list it is called on. 
The sorted() function will create a new list containing a sorted version of the list it is given. 
The sorted() function will not modify the list passed as a parameter. 
If you want to sort a list but still have the original unsorted version, then you would use the sorted() function. 
If maintaining the original order of the list is unimportant, then you can call the sort() function on the list.

  Difference between reverse and reversed?

Ans. reverse() actually reverses the elements in the container. reversed() doesn't actually reverse anything,
     it merely returns an object that can be used to iterate over the container's elements in reverse order.

 Difference between copy and deepcopy?

Ans. A deep copy creates a new object and recursively adds the copies of nested objects present in the original elements. 
However, we are going to create deep copy using deepcopy() function present in copy module whereas copy() function simply copies the elements.

  How to remove duplicate elements in the list?

Ans. To remove duplicates from a given list, you can make use of an empty temporary list. 
     For that first, you will have to loop through the list having duplicates and add the unique items to the temporary list.
     Later the temporary list is assigned to the main list."""

my_list = [10, 20, 30, 10, 20, 40, 50, 40 ,60, 20]
print("List Before ", my_list)
temp_list = [] 
for i in my_list:
  if i not in temp_list:
    temp_list.append(i)
my_list = temp_list
print("List After removing duplicates ", my_list)

List Before  [10, 20, 30, 10, 20, 40, 50, 40, 60, 20]
List After removing duplicates  [10, 20, 30, 40, 50, 60]


In [ ]:
   """How to find an index of an element in the python list?

Ans. list.index(element, start, end) : this is the syntax we can use to find the index of particular range of elements in the list.

    How to find the occurrences of an element in the python list?

Ans. count() function is used to find how many times an element has appeared in the list.
  
     How to insert an item at a given position?"""

l=[10,20,30,40,50]
print('List before: ',l)
l.insert(1,500)
print('List after: ', l)

List before:  [10, 20, 30, 40, 50]
List after:  [10, 500, 20, 30, 40, 50]


In [ ]:
#How to check if an item is in the list?


l=[1,2,3,4]
print(l)

for i in l:
  if(i == 4) :
    print ("Element Exists")

[1, 2, 3, 4]
Element Exists


In [ ]:
"""How to flatten a list in python?

Flattening a list of lists entails converting a 2D list into a 1D list by un-nesting each list item stored in the list of lists - i.e.,
 converting [[1, 2, 3], [4, 5, 6], [7, 8, 9]] into [1, 2, 3, 4, 5, 6, 7, 8, 9]."""

mylist = [[1,2,3],[4,5,6],[7,8,9]]
print("Original List : ",mylist)
print("Flattened List : ",end=" ")
for lst in mylist:
  for val in lst:
    print(val, end= " ")

Original List :  [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
Flattened List :  1 2 3 4 5 6 7 8 9 

In [ ]:
#How to convert python list to other data structures like set, tuple, dictionary?

l=[1,2,3,4,5]
print(set(l))
print(tuple(l))
print(dict({"val":l}))

{1, 2, 3, 4, 5}
(1, 2, 3, 4, 5)
{'val': [1, 2, 3, 4, 5]}


In [ ]:
"""How to apply a function to all items in the list?

Ans. map() function is used to apply a function to all the elements present in the list."""

a_list = ["a", "b", "c"]
map_object = map(str.upper, a_list)
#capitalize each letter
new_list = list(map_object)
print(new_list)

['A', 'B', 'C']


In [ ]:
"""How to filter the elements based on a function in a python list?

Ans. Python has a built-in function called filter() that allows you to filter a list (or a tuple) in a more beautiful way. 
The filter() function iterates over the elements of the list and applies the fn() function to each element. 
It returns an iterator for the elements where the fn() returns True ."""

scores = [70, 60, 80, 90, 50]
filtered = []
for score in scores:
  if score >= 80:
    filtered.append(score)
print(filtered)

[80, 90]


How python lists are stored in memory?

Ans. Instead of storing values in the memory space reserved by the variable, Python has the variable refer to the value. Similar to pointers in C, variables in Python refer to values (or objects) stored somewhere in memory.

#Task-3

In [ ]:
#Write a Python Program to sort (ascending and descending) a dictionary by value.

import operator
d = {10: 20, 30: 40, 40: 30, 20: 10, 0: 0}
print('Original dictionary : ',d)
sorted_d = sorted(d.items(), key=operator.itemgetter(1))
print('Dictionary in ascending order by value : ',sorted_d)
sorted_d = dict( sorted(d.items(), key=operator.itemgetter(1),reverse=True))
print('Dictionary in descending order by value : ',sorted_d)

Original dictionary :  {10: 20, 30: 40, 40: 30, 20: 10, 0: 0}
Dictionary in ascending order by value :  [(0, 0), (20, 10), (10, 20), (40, 30), (30, 40)]
Dictionary in descending order by value :  {30: 40, 40: 30, 10: 20, 20: 10, 0: 0}


In [ ]:
"""Write a Python Program to add a key to a dictionary.

Sample Dictionary : {0: 10, 1: 20}

Expected Result : {0: 10, 1: 20, 2: 30}"""

d={0:10,1:20}
d[2]=30
print(d)

{0: 10, 1: 20, 2: 30}


In [ ]:
"""Write a program asks for City name and Temperature and builds a dictionary using that Later on you can input City name and
  it will tell you the Temperature of that City."""

n=int(input('Enter no of entries : '))
while n>0:
  city=input('Enter city name : ') 
  temp=int(input('Enter temperature : '))
  d[city]=temp
  n=n-1
city=input('Enter city name : ')
print(f'Tempreature in {city} is {d[city]}')

Enter no of entries : 2
Enter city name : allahbad
Enter temperature : 30
Enter city name : ayodhya
Enter temperature : 45
Enter city name : ayodhya
Tempreature in ayodhya is 45


In [ ]:
"""Write a Python program to convert list to list of dictionaries.
Sample lists: ["Black", "Red", "Maroon", "Yellow"], ["#000000", "#FF0000", "#800000", "#FFFF00"]

Expected Output: [{'color_name': 'Black', 'color_code': '#000000'}, {'color_name': 'Red', 'color_code': '#FF0000'}, {'color_name': 'Maroon', 'color_code': '#800000'},
 {'color_name': 'Yellow', 'color_code': '#FFFF00'}]"""

l1=["Black", "Red", "Maroon", "Yellow"]
l2=["#000000", "#FF0000", "#800000", "#FFFF00"]
result=[{'color_name':cname,'color_code':ccode}
for cname,ccode in zip(l1,l2)]
print(result)

[{'color_name': 'Black', 'color_code': '#000000'}, {'color_name': 'Red', 'color_code': '#FF0000'}, {'color_name': 'Maroon', 'color_code': '#800000'}, {'color_name': 'Yellow', 'color_code': '#FFFF00'}]


In [ ]:
"""We have following information on Employees and their Salary (Salary is in lakhs),
Employee Salary

John 14

Smith 13

Alice 32

Daneil 21

Using above create a dictionary of Employees and their Salary Write a program that asks user for three type of inputs,

print: if user enter print then it should print all Employees with their Salary in this format,

John ==>14

Smith ==>13

Alice ==>32

Daneil ==>21

add: if user input adds then it should further ask for an Employee name to add.
 If Employee already exists in our dataset then it should print that it exists and do nothing.
  If it doesn't then it asks for Salary and add that new Employee/Salary in our dictionary and print it

remove: when user inputs remove it should ask for an Employee to remove.
 If an Employee exists in our dictionary then remove it and print a new dictionary using format shown above in (a). Else print that Employee doesn't exist!

query: on this again ask the user for which Employee he or she wants to query. When a user inputs that Employee it will print the Salary of that Employee."""

di={'John':14,'Smith':13,'Alice':32,'Daniel':21}
inp=input('Enter print/add/remove or query')
if inp=='print':
  for key in di.keys():
    print(f'{key} ==>{di[key]}')
elif inp=='add':
    key=input('Enter employee name : ')
    if key in di:
      print('It exists')
    else:
      sal=input('Enter Salary : ')
      di[key]=sal    
      print(f'{key} ==>{sal}')
elif inp=='remove':
  key=input('Enter employee name : ')
  if key not in di:
    print('Employee doesn\'t exists')
  else:
    val=di[key]
    di.pop(key)
    print(f'{key} ==>{val}')
elif inp=='query':
  key=input("Enter employee name")
  print(di[key])

Enter print/add/remove or queryadd
Enter employee name : John
It exists


In [ ]:
"""What is the difference between a set and a frozenset? Create any set and try to use frozenset(setname).

Ans. The frozenset() function returns an immutable frozenset object initialized with elements from the given iterable. 
Frozen set is just an immutable version of a Python set object. While elements of a set can be modified at any time,
 elements of the frozen set remain the same after creation."""

s={1,2,3,4,5}
s1=frozenset(s)
s.add(6)
print(s)
s1.add(6)
#s is a set and s1 is a frozenset

{1, 2, 3, 4, 5, 6}


AttributeError: ignored

In [ ]:
"""Find the elements in a given set that are not in another set

set1 = {10,20,30,40,50}

set2 = {40,50,60,70,80}

Difference between set1 and set2 is {10,20,30}"""


set1 = {10,20,30,40,50}
set2 = {40,50,60,70,80}
diff=set()
for i in set1:
  if i not in set2:
    diff.add(i)
print(f'Difference between set1 and set2 is {diff}')

Difference between set1 and set2 is {10, 20, 30}


#Task-4

In [ ]:
#Import the numpy package under the name np and Print the numpy version and the configuration

import numpy as np
print(np.__version__)

1.19.5


In [ ]:
# Creat a Null vector of size 10
x = np.zeros(10)
print("Null vector of size 10",x)

Null vector of size 10 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
#Create Simple 1-D array and check type and check data types in array
x = np.array([10,20,30,40,50,60,70])
print("type:",type(x))
print("Data type:",x.dtype)

type: <class 'numpy.ndarray'>
Data type: int64


In [ ]:
#How to find number of dimensions, bytes per element and bytes of memory used?

x.ndim

1

In [ ]:
x.itemsize

8

In [ ]:
x.nbytes

56

In [ ]:
x.shape

(7,)

In [ ]:
#Create a null vector of size 10 but the fifth value which is 1
x_arr= np.zeros(10)
x_arr[4]=1
print(x_arr)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [ ]:
#Create a vector with values ranging from 10 to 49
vector=np.arange(10,50)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
#Reverse a vector (first element becomes last)
print("Original vector:",vector)
print("/nReversed vector:",np.flip(vector))

Original vector: [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
/nReversed vector: [49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [ ]:
a = np.array([10,20,30,40,50,60,70,80])
a[::-1]

array([80, 70, 60, 50, 40, 30, 20, 10])

In [ ]:
#Create a 3x3 matrix with values ranging from 0 to 8
a = np.arange(0,9)
a.reshape(3,3)



array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [31]:
#Find indices of non-zero elements from [1,2,0,0,4,0]
arr1=[1,2,0,0,4,0]
arr1
np.nonzero(arr1)

(array([0, 1, 4]),)

In [32]:
#Create a 3x3 identity matrix

np.identity(3)
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [35]:
np.random.random((3,3,3))

array([[[0.80321697, 0.60450911, 0.31819198],
        [0.96503658, 0.41361518, 0.9145643 ],
        [0.61286442, 0.55828939, 0.90344872]],

       [[0.91629743, 0.72907272, 0.90310882],
        [0.49978919, 0.4468349 , 0.39264264],
        [0.5306432 , 0.96870138, 0.76421027]],

       [[0.25560738, 0.74126047, 0.34273453],
        [0.30763708, 0.12419458, 0.57707357],
        [0.92829634, 0.50454175, 0.98184859]]])

In [37]:
#Create a 10x10 array with random values and find the minimum and maximum values
matrix = np.random.random((10,10))
print("matrix:",matrix)
print("max value:", matrix.max())
print("min value:", matrix.min())

matrix: [[0.93577104 0.64093725 0.78718824 0.08506358 0.13132302 0.60296796
  0.73038002 0.93114856 0.33325998 0.56519491]
 [0.80479074 0.34520618 0.59407491 0.66109406 0.99355002 0.0963557
  0.02965484 0.96266245 0.51210442 0.62666472]
 [0.65242394 0.25718968 0.29499676 0.16142858 0.84698036 0.25183063
  0.3131195  0.64066754 0.47060979 0.96302642]
 [0.88353965 0.970256   0.17279662 0.43973314 0.71270895 0.71892449
  0.99931316 0.54161389 0.3248047  0.61165228]
 [0.02286376 0.22314043 0.38629427 0.78939987 0.03586637 0.44739565
  0.97283946 0.51277758 0.29978292 0.83508091]
 [0.00258142 0.04777251 0.86559096 0.75730408 0.85013936 0.25265544
  0.1526586  0.6464196  0.82910814 0.01981916]
 [0.3815855  0.66094067 0.91626216 0.6629838  0.55528854 0.06715266
  0.90349089 0.68964744 0.28023712 0.88520962]
 [0.83986663 0.69708488 0.09423684 0.62272482 0.52940908 0.36277266
  0.14999054 0.26981593 0.16633724 0.78740701]
 [0.62493574 0.44071436 0.09776548 0.33667645 0.51682245 0.54576751
  0.6

In [38]:
#Create a random vector of size 30 and find the mean value
vector = np.random.random(30)
print("vector:",vector)
print("vector min:",vector.min())

vector: [0.65450081 0.97092472 0.59335358 0.62491503 0.71333065 0.4031448
 0.48972204 0.15013229 0.66677552 0.34157771 0.8112108  0.12363888
 0.09045403 0.86102262 0.48836492 0.90013562 0.80565187 0.05254771
 0.20451738 0.66633474 0.22785764 0.1718109  0.71299096 0.95405463
 0.38238951 0.50430887 0.5348775  0.53461177 0.00442557 0.10168516]
vector min: 0.004425573579884823


In [40]:
#Create a 2d array with 1 on the border and 0 inside
x = np.ones((5,5))
x[1:4,1:4] = 0
x

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [41]:
#How to add a border (filled with 0's) around an existing array?

x = np.ones((5,5))
x[:1,:] = 0
x[4:,:] = 0
x[:,:1] = 0
x[:,4:] = 0
x 

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

In [43]:
"""How to Accessing/Changing specific elements, rows, columns, etc in Numpy array?

Example - [[ 1 2 3 4 5 6 7] [ 8 9 10 11 12 13 14]]

i Get 13

ii get first row only

iii get 3rd column only

iv get [2, 4, 6]

v replace 13 by 20"""

array = np.array([
                  [ 1, 2, 3, 4, 5, 6, 7],
                  [ 8, 9, 10, 11, 12, 13, 14]])
print("Accessing Element 13 :", array[1,5])
print("First Row", array[0])
print("Third Column", array[:,2])
print(array[0,1:7:2])
array[1,5] = 20
print("Replace 13 by 20")
print(array)

Accessing Element 13 : 13
First Row [1 2 3 4 5 6 7]
Third Column [ 3 10]
[2 4 6]
Replace 13 by 20
[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [47]:
#How to Convert a 1D array to a 2D array with 2 rows

randomArray = np.random.random(10)
randomArray = randomArray.reshape(2,5)
randomArray

array([[0.8908441 , 0.53191095, 0.91866126, 0.64377966, 0.15626501],
       [0.60692432, 0.11662338, 0.62353812, 0.31929637, 0.1370228 ]])

In [49]:
"""Create the following pattern without hardcoding. Use only numpy functions and the below input array a.

Input: a = np.array([1,2,3])`

Desired Output:

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])"""

a = np.array([1,2,3])
print(a) 

a = np.append(np.repeat(a,3),np.tile(a,3))
print(a)

[1 2 3]
[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


In [51]:
#Write a program to show how Numpy taking less memory compared to Python List?

l=range(1000)
import sys
a=10
print("Size of list :",sys.getsizeof(a)*len(l))
a1=np.arange(1000)
print("Size of nupy array",a1.size*a1.itemsize)

Size of list : 28000
Size of nupy array 8000


In [52]:
#Write a program to show how Numpy taking less time compared to Python List?

import time
import sys
size=1000000
l1=range(size)
l2=range(size)
n1=np.arange(size)
n2=np.arange(size)
start=time.time()
result=[(x+y)for x,y in zip(l1,l2)]
print("time taken by list :",(time.time()-start)*1000)
start=time.time()
res1=n1+n2
print("time taken by numpy array :",(time.time()-start)*1000)

time taken by list : 156.12483024597168
time taken by numpy array : 4.724740982055664


#Task-5

In [54]:
import numpy as np
import pandas as pd

In [92]:
#Load the IMDb Dataset and read
df = pd.read_csv("IMDB-Movie-Data.csv")

In [93]:
df

Rank                    Title  ... Revenue (Millions) Metascore
0       1  Guardians of the Galaxy  ...             333.13      76.0
1       2               Prometheus  ...             126.46      65.0
2       3                    Split  ...             138.12      62.0
3       4                     Sing  ...             270.32      59.0
4       5            Suicide Squad  ...             325.02      40.0
..    ...                      ...  ...                ...       ...
995   996     Secret in Their Eyes  ...                NaN      45.0
996   997          Hostel: Part II  ...              17.54      46.0
997   998   Step Up 2: The Streets  ...              58.01      50.0
998   999             Search Party  ...                NaN      22.0
999  1000               Nine Lives  ...              19.64      11.0

[1000 rows x 12 columns]

In [94]:
#View the dataset
df.head()

Rank                    Title  ... Revenue (Millions) Metascore
0     1  Guardians of the Galaxy  ...             333.13      76.0
1     2               Prometheus  ...             126.46      65.0
2     3                    Split  ...             138.12      62.0
3     4                     Sing  ...             270.32      59.0
4     5            Suicide Squad  ...             325.02      40.0

[5 rows x 12 columns]

In [95]:
df.dtypes

Rank                    int64
Title                  object
Genre                  object
Description            object
Director               object
Actors                 object
Year                    int64
Runtime (Minutes)       int64
Rating                float64
Votes                   int64
Revenue (Millions)    float64
Metascore             float64
dtype: object

In [96]:
df.columns 

Index(['Rank', 'Title', 'Genre', 'Description', 'Director', 'Actors', 'Year',
       'Runtime (Minutes)', 'Rating', 'Votes', 'Revenue (Millions)',
       'Metascore'],
      dtype='object')

In [97]:
df.axes

[RangeIndex(start=0, stop=1000, step=1),
 Index(['Rank', 'Title', 'Genre', 'Description', 'Director', 'Actors', 'Year',
        'Runtime (Minutes)', 'Rating', 'Votes', 'Revenue (Millions)',
        'Metascore'],
       dtype='object')]

In [98]:
df.ndim

2

In [99]:
df.size

12000

In [100]:
df.shape

(1000, 12)

In [101]:
df.describe()

Rank         Year  ...  Revenue (Millions)   Metascore
count  1000.000000  1000.000000  ...          872.000000  936.000000
mean    500.500000  2012.783000  ...           82.956376   58.985043
std     288.819436     3.205962  ...          103.253540   17.194757
min       1.000000  2006.000000  ...            0.000000   11.000000
25%     250.750000  2010.000000  ...           13.270000   47.000000
50%     500.500000  2014.000000  ...           47.985000   59.500000
75%     750.250000  2016.000000  ...          113.715000   72.000000
max    1000.000000  2016.000000  ...          936.630000  100.000000

[8 rows x 7 columns]

In [102]:
df.head(70).mean()

Rank                      35.500000
Year                    2015.314286
Runtime (Minutes)        117.428571
Rating                     6.945714
Votes                 210839.757143
Revenue (Millions)       142.910645
Metascore                 62.343750
dtype: float64

In [103]:
df.tail(70).mean()

Rank                    965.500000
Year                   2012.200000
Runtime (Minutes)       107.971429
Rating                    6.345714
Votes                 76213.485714
Revenue (Millions)       42.602727
Metascore                50.322581
dtype: float64

In [104]:
#Data Selection – Indexing and Slicing data

df_year=df["Year"]
df_year

0      2014
1      2012
2      2016
3      2016
4      2016
       ... 
995    2015
996    2007
997    2008
998    2014
999    2016
Name: Year, Length: 1000, dtype: int64

In [105]:
df["Genre"]

0       Action,Adventure,Sci-Fi
1      Adventure,Mystery,Sci-Fi
2               Horror,Thriller
3       Animation,Comedy,Family
4      Action,Adventure,Fantasy
                 ...           
995         Crime,Drama,Mystery
996                      Horror
997         Drama,Music,Romance
998            Adventure,Comedy
999       Comedy,Family,Fantasy
Name: Genre, Length: 1000, dtype: object

In [106]:
#Data Selection – Based on Conditional filtering

mostearned=df[df['Revenue (Millions)']==df['Revenue (Millions)'].max()]
print(mostearned)

    Rank  ... Metascore
50    51  ...      81.0

[1 rows x 12 columns]


In [107]:
imdbtop=df[["Title","Director","Rating"]][df["Rating"]==df["Rating"].max()]
imdbtop.head()

Title           Director  Rating
54  The Dark Knight  Christopher Nolan     9.0

In [108]:
#Groupby operations

directors=df.groupby("Director")["Rating"].mean().reset_index()
directors.sort_values("Rating", ascending=False)

Director  Rating
465                     Nitesh Tiwari    8.80
108                 Christopher Nolan    8.68
392                    Makoto Shinkai    8.60
470                   Olivier Nakache    8.60
194  Florian Henckel von Donnersmarck    8.50
..                                ...     ...
435                    Micheal Bafaro    3.50
329                 Jonathan Holbrook    3.20
274                        James Wong    2.70
566                     Shawn Burkett    2.70
277                   Jason Friedberg    1.90

[644 rows x 2 columns]

In [113]:
#Sorting operation
df_sorted=df.sort_values(by='Director')
df_sorted.head()

Rank             Title  ... Revenue (Millions) Metascore
991   992  Taare Zameen Par  ...               1.20      42.0
311   312    La vie d'Adèle  ...               2.20      88.0
783   784            Tramps  ...                NaN      77.0
142   143     The Big Short  ...              70.24      81.0
469   470    The Other Guys  ...             119.22      64.0

[5 rows x 12 columns]

In [114]:
df.sort_index(ascending=True)

Rank                    Title  ... Revenue (Millions) Metascore
0       1  Guardians of the Galaxy  ...             333.13      76.0
1       2               Prometheus  ...             126.46      65.0
2       3                    Split  ...             138.12      62.0
3       4                     Sing  ...             270.32      59.0
4       5            Suicide Squad  ...             325.02      40.0
..    ...                      ...  ...                ...       ...
995   996     Secret in Their Eyes  ...                NaN      45.0
996   997          Hostel: Part II  ...              17.54      46.0
997   998   Step Up 2: The Streets  ...              58.01      50.0
998   999             Search Party  ...                NaN      22.0
999  1000               Nine Lives  ...              19.64      11.0

[1000 rows x 12 columns]

In [115]:
df.sort_index(ascending=False)

Rank                    Title  ... Revenue (Millions) Metascore
999  1000               Nine Lives  ...              19.64      11.0
998   999             Search Party  ...                NaN      22.0
997   998   Step Up 2: The Streets  ...              58.01      50.0
996   997          Hostel: Part II  ...              17.54      46.0
995   996     Secret in Their Eyes  ...                NaN      45.0
..    ...                      ...  ...                ...       ...
4       5            Suicide Squad  ...             325.02      40.0
3       4                     Sing  ...             270.32      59.0
2       3                    Split  ...             138.12      62.0
1       2               Prometheus  ...             126.46      65.0
0       1  Guardians of the Galaxy  ...             333.13      76.0

[1000 rows x 12 columns]

In [116]:
df.sort_values(by=['Genre','Director'],ascending=[True,False])

Rank                   Title  ... Revenue (Millions) Metascore
123   124    Boyka: Undisputed IV  ...                NaN       NaN
580   581    Kickboxer: Vengeance  ...             131.56      37.0
344   345            Spider-Man 3  ...             336.53      59.0
368   369  The Amazing Spider-Man  ...             262.03      66.0
284   285                Hercules  ...              72.66      47.0
..    ...                     ...  ...                ...       ...
942   943              Transpecos  ...                NaN      73.0
933   934                  Detour  ...                NaN      46.0
746   747      Only for One Night  ...                NaN      60.0
729   730               The Guest  ...               0.32      76.0
160   161                    Mine  ...                NaN      40.0

[1000 rows x 12 columns]

In [117]:
#Dealing with missing values

df.isna().any()

Rank                  False
Title                 False
Genre                 False
Description           False
Director              False
Actors                False
Year                  False
Runtime (Minutes)     False
Rating                False
Votes                 False
Revenue (Millions)     True
Metascore              True
dtype: bool

In [118]:
print(df.isna().sum())

Rank                    0
Title                   0
Genre                   0
Description             0
Director                0
Actors                  0
Year                    0
Runtime (Minutes)       0
Rating                  0
Votes                   0
Revenue (Millions)    128
Metascore              64
dtype: int64


In [120]:
#Dropping columns and null values

imdb_data_cleaned = df.dropna()
imdb_data_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 838 entries, 0 to 999
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   Rank                838 non-null    int64  
 1   Title               838 non-null    object 
 2   Genre               838 non-null    object 
 3   Description         838 non-null    object 
 4   Director            838 non-null    object 
 5   Actors              838 non-null    object 
 6   Year                838 non-null    int64  
 7   Runtime (Minutes)   838 non-null    int64  
 8   Rating              838 non-null    float64
 9   Votes               838 non-null    int64  
 10  Revenue (Millions)  838 non-null    float64
 11  Metascore           838 non-null    float64
dtypes: float64(3), int64(4), object(5)
memory usage: 85.1+ KB


In [121]:
#Apply( ) functions


top_rated.groupby("Director")[["Rating", "Metascore"]].agg([np.mean, np.median]).sort_values(
    [("Rating","mean"),("Metascore", "mean")], ascending = False).head(n=15)

Rating        Metascore       
                                   mean median      mean median
Director                                                       
Nitesh Tiwari                      8.80   8.80       NaN    NaN
Christopher Nolan                  8.68   8.60      74.8   74.0
Makoto Shinkai                     8.60   8.60      79.0   79.0
Olivier Nakache                    8.60   8.60      57.0   57.0
Florian Henckel von Donnersmarck   8.50   8.50      89.0   89.0
Aamir Khan                         8.50   8.50      42.0   42.0
Damien Chazelle                    8.40   8.40      90.5   90.5
Naoko Yamada                       8.40   8.40      80.0   80.0
Lee Unkrich                        8.30   8.30      92.0   92.0
Thomas Vinterberg                  8.30   8.30      76.0   76.0
Amber Tamblyn                      8.30   8.30      71.0   71.0
Rajkumar Hirani                    8.30   8.30      59.0   59.0
S.S. Rajamouli                     8.30   8.30       NaN    NaN
Pete Docter                        8.25   8.25      91.0   91.0
Lenny Abrahamson                   8.20   8.20      86.0   86.0

In [122]:
top_rated_revenue = imdb_data_cleaned.sort_values(["Rating","Metascore"], ascending=False)[
    ["Title", "Director", "Rating","Metascore", "Revenue (Millions)"]]
top_rated_revenue.index = range(1,839)
top_rated_revenue.head(n=15)

Title  ... Revenue (Millions)
1         The Dark Knight  ...             533.32
2               Inception  ...             292.57
3           Kimi no na wa  ...               4.68
4            Interstellar  ...             187.99
5        The Intouchables  ...              13.18
6     The Lives of Others  ...              11.28
7                Whiplash  ...              13.09
8            The Departed  ...             132.37
9   The Dark Knight Rises  ...             448.13
10           The Prestige  ...              53.08
11       Taare Zameen Par  ...               1.20
12       Django Unchained  ...             162.80
13               3 Idiots  ...               6.52
14             La La Land  ...             151.06
15            Toy Story 3  ...             414.98

[15 rows x 5 columns]